export enum BusinessOnboardingStatus {
    DRAFT = 'DRAFT', // Created but incomplete
    PROFILE_COMPLETED = 'PROFILE_COMPLETED',
    SERVICES_ADDED = 'SERVICES_ADDED',
    PAYMENT_CONNECTED = 'PAYMENT_CONNECTED',
    WHATSAPP_CONNECTED = 'WHATSAPP_CONNECTED',
    COMPLETED = 'COMPLETED',
}